package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"strings"

	"github.com/amirfakhrullah/go-graphql/database"
	"github.com/amirfakhrullah/go-graphql/graph/customTypes"
	"github.com/amirfakhrullah/go-graphql/graph/generated"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, text string) (*customTypes.Todo, error) {
	context := database.GetContext(ctx)
	todo := &customTypes.Todo{
		ID: strings.Join(strings.Split(text, " "), "-"),
		Text: text,
		Done: false,
	}
	if err := context.Database.Create(&todo).Error; err != nil {
		return nil, err
	}
	return todo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input customTypes.TodoInput) (*customTypes.Todo, error) {
	context := database.GetContext(ctx)
	todo := &customTypes.Todo{
		ID:   input.ID,
		Text: input.Text,
		Done: input.Done,
	}
	if err := context.Database.Save(&todo).Error; err != nil {
		return nil, err
	}
	return todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*customTypes.Todo, error) {
	context := database.GetContext(ctx)
	var todo *customTypes.Todo

	if err := context.Database.Where("id = ?", id).Delete(&todo).Error; err != nil {
		return nil, err
	}
	return todo, nil
}

// GetTodos is the resolver for the getTodos field.
func (r *queryResolver) GetTodos(ctx context.Context) ([]*customTypes.Todo, error) {
	context := database.GetContext(ctx)
	var todos []*customTypes.Todo
	if err := context.Database.Find(&todos).Error; err != nil {
		return nil, err
	}
	return todos, nil
}

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context, id string) (*customTypes.Todo, error) {
	context := database.GetContext(ctx)
	var todo *customTypes.Todo
	if err := context.Database.Find(&todo, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return todo, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
